-- Migration: Team Invites

-- 1. TEAM INVITES TABLE
CREATE TABLE IF NOT EXISTS public.team_invites (
  id bigint generated by default as identity primary key,
  team_id bigint references public.teams(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  status text default 'pending' check (status in ('pending', 'accepted', 'rejected')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(team_id, user_id)
);

-- Enable RLS
ALTER TABLE public.team_invites ENABLE ROW LEVEL SECURITY;

-- Policies
-- View: users can see invites sent to them, team members can see invites sent by their team
DROP POLICY IF EXISTS "View own invites" ON public.team_invites;
CREATE POLICY "View own invites"
  ON public.team_invites FOR SELECT
  USING ( 
    auth.uid() = user_id OR 
    EXISTS (
      SELECT 1 FROM public.team_members
      WHERE team_members.team_id = team_invites.team_id
      AND team_members.user_id = auth.uid()
    )
  );

-- Insert: Team members (captains/admins?) can invite. For now, let's say any member or just captains.
-- Let's stick to captains for "invite" rights usually, but for simplicity, any team member? 
-- The prompt didn't specify, but "captain" logic was in MyTeam.js. Let's restrict to team members.
DROP POLICY IF EXISTS "Team members can invite" ON public.team_invites;
CREATE POLICY "Team members can invite"
  ON public.team_invites FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.team_members
      WHERE team_members.team_id = team_invites.team_id
      AND team_members.user_id = auth.uid()
    )
  );

-- Update: The invited user can accept/reject (status update)
DROP POLICY IF EXISTS "Invited user can respond" ON public.team_invites;
CREATE POLICY "Invited user can respond"
  ON public.team_invites FOR UPDATE
  USING ( auth.uid() = user_id );
