-- Migration: Add Groups, Matches, and Qualifications System (Idempotent)

-- 1. GROUPS Table
CREATE TABLE IF NOT EXISTS public.groups (
  id bigint generated by default as identity primary key,
  tournament_id bigint references public.tournaments(id) on delete cascade not null,
  stage_name text not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public view groups" ON public.groups;
CREATE POLICY "Public view groups" ON public.groups FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin manage groups" ON public.groups;
CREATE POLICY "Admin manage groups" ON public.groups FOR ALL USING (
  exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'super_admin'))
);

-- 2. GROUP_TEAMS Table
CREATE TABLE IF NOT EXISTS public.group_teams (
  id bigint generated by default as identity primary key,
  group_id bigint references public.groups(id) on delete cascade not null,
  team_id bigint references public.teams(id) on delete cascade not null,
  assigned_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(group_id, team_id)
);
ALTER TABLE public.group_teams ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public view group teams" ON public.group_teams;
CREATE POLICY "Public view group teams" ON public.group_teams FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admin manage group teams" ON public.group_teams;
CREATE POLICY "Admin manage group teams" ON public.group_teams FOR ALL USING (
  exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'super_admin'))
);

-- 3. MATCHES Table
CREATE TABLE IF NOT EXISTS public.matches (
  id bigint generated by default as identity primary key,
  group_id bigint references public.groups(id) on delete cascade not null,
  start_time timestamp with time zone not null,
  room_id text,
  room_password text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins full access matches" ON public.matches;
CREATE POLICY "Admins full access matches" ON public.matches FOR ALL USING (
  exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'super_admin'))
);

DROP POLICY IF EXISTS "Public view matches schedule" ON public.matches;
CREATE POLICY "Public view matches schedule" ON public.matches FOR SELECT USING (true);


-- 4. MATCH CREDENTIALS Table
CREATE TABLE IF NOT EXISTS public.match_credentials (
  match_id bigint references public.matches(id) on delete cascade primary key,
  room_id text,
  room_password text
);
ALTER TABLE public.match_credentials ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins view credentials" ON public.match_credentials;
CREATE POLICY "Admins view credentials" ON public.match_credentials FOR ALL USING (
  exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'super_admin'))
);

DROP POLICY IF EXISTS "Players view credentials near match time" ON public.match_credentials;
CREATE POLICY "Players view credentials near match time" ON public.match_credentials FOR SELECT USING (
  auth.role() = 'authenticated' AND
  exists (
    select 1 from public.matches m 
    where m.id = match_credentials.match_id 
    and now() >= (m.start_time - interval '15 minutes')
  ) AND
  exists (
    select 1 from public.matches m
    join public.group_teams gt on m.group_id = gt.group_id
    join public.team_members tm on gt.team_id = tm.team_id
    where m.id = match_credentials.match_id
    and tm.user_id = auth.uid()
  )
);

-- 5. QUALIFICATIONS Table
CREATE TABLE IF NOT EXISTS public.qualifications (
  id bigint generated by default as identity primary key,
  tournament_id bigint references public.tournaments(id) on delete cascade not null,
  team_id bigint references public.teams(id) on delete cascade not null,
  from_stage text not null,
  to_stage text not null,
  qualified_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(tournament_id, team_id, from_stage)
);
ALTER TABLE public.qualifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public view qualifications" ON public.qualifications;
CREATE POLICY "Public view qualifications" ON public.qualifications FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins manage qualifications" ON public.qualifications;
CREATE POLICY "Admins manage qualifications" ON public.qualifications FOR ALL USING (
  exists (select 1 from public.profiles where id = auth.uid() and role in ('admin', 'super_admin'))
);
