-- Migration: Add Team Functionality & Tournament Registration

-- 1. Add join_code to teams
ALTER TABLE public.teams 
ADD COLUMN IF NOT EXISTS join_code TEXT UNIQUE;

-- 2. Enable Users to Insert Teams
DROP POLICY IF EXISTS "Users can insert teams" ON public.teams;
CREATE POLICY "Users can insert teams"
  ON public.teams FOR INSERT
  TO authenticated
  WITH CHECK ( true );


-- 3. TEAM MEMBERS TABLE
CREATE TABLE IF NOT EXISTS public.team_members (
  id bigint generated by default as identity primary key,
  team_id bigint references public.teams(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  role text default 'member',
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(user_id)
);

-- Enable RLS
ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;

-- Policies for team_members
DROP POLICY IF EXISTS "Team members are viewable by everyone" ON public.team_members;
CREATE POLICY "Team members are viewable by everyone"
  ON public.team_members FOR SELECT
  USING ( true );

DROP POLICY IF EXISTS "Users can join teams" ON public.team_members;
CREATE POLICY "Users can join teams"
  ON public.team_members FOR INSERT
  WITH CHECK ( auth.uid() = user_id );

DROP POLICY IF EXISTS "Users can leave teams" ON public.team_members;
CREATE POLICY "Users can leave teams"
  ON public.team_members FOR DELETE
  USING ( auth.uid() = user_id );


-- 4. TOURNAMENT REGISTRATIONS TABLE
CREATE TABLE IF NOT EXISTS public.tournament_registrations (
  id bigint generated by default as identity primary key,
  tournament_id bigint references public.tournaments(id) on delete cascade not null,
  team_id bigint references public.teams(id) on delete cascade not null,
  registered_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(tournament_id, team_id)
);

-- Enable RLS
ALTER TABLE public.tournament_registrations ENABLE ROW LEVEL SECURITY;

-- Policies for tournament_registrations
DROP POLICY IF EXISTS "Registrations viewable by everyone" ON public.tournament_registrations;
CREATE POLICY "Registrations viewable by everyone"
  ON public.tournament_registrations FOR SELECT
  USING ( true );

DROP POLICY IF EXISTS "Team members can register" ON public.tournament_registrations;
CREATE POLICY "Team members can register"
  ON public.tournament_registrations FOR INSERT
  WITH CHECK ( 
    EXISTS (
      SELECT 1 FROM public.team_members 
      WHERE team_members.team_id = tournament_registrations.team_id
      AND team_members.user_id = auth.uid()
    )
  );
