-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. ENUMS & ROLES
create type user_role as enum ('super_admin', 'admin', 'user');

-- 2. PROFILES TABLE (Extends auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  avatar_url text,
  role user_role default 'user'::user_role,
  updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Trigger to handle new user signup automatically
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 'user');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 3. TOURNAMENTS TABLE
create table public.tournaments (
  id bigint generated by default as identity primary key,
  name text not null,
  game text not null,
  prize text not null,
  start_date text not null,
  image_url text,
  max_teams integer default 16,
  total_stages integer default 5,
  stages text[] default ARRAY['Qualifiers', 'Quarter Finals', 'Semi Finals', 'Finals', 'Grand Finals'],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.tournaments enable row level security;

-- Policies for tournaments
create policy "Tournaments are viewable by everyone."
  on public.tournaments for select
  using ( true );

create policy "Admins and Super Admins can insert tournaments."
  on public.tournaments for insert
  with check ( 
    auth.uid() in (
      select id from public.profiles 
      where role in ('admin', 'super_admin')
    )
  );

create policy "Admins and Super Admins can update tournaments."
  on public.tournaments for update
  using ( 
    auth.uid() in (
      select id from public.profiles 
      where role in ('admin', 'super_admin')
    )
  );

create policy "Admins and Super Admins can delete tournaments."
  on public.tournaments for delete
  using ( 
    auth.uid() in (
      select id from public.profiles 
      where role in ('admin', 'super_admin')
    )
  );


-- 4. TEAMS TABLE
create table public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  wins integer default 0,
  members_count integer default 1,
  logo_url text,
  join_code text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.teams enable row level security;

-- Policies for teams
create policy "Teams are viewable by everyone."
  on public.teams for select
  using ( true );

create policy "Admins and Super Admins can manage teams."
  on public.teams for all
  using ( 
    auth.uid() in (
      select id from public.profiles 
      where role in ('admin', 'super_admin')
    )
  );

create policy "Users can insert teams"
  on public.teams for insert
  to authenticated
  with check ( true );


-- 6. TEAM MEMBERS TABLE (New)
create table public.team_members (
  id bigint generated by default as identity primary key,
  team_id bigint references public.teams(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  role text default 'member',
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id)
);

-- Enable RLS
alter table public.team_members enable row level security;

-- Policies
create policy "Team members are viewable by everyone"
  on public.team_members for select
  using ( true );

create policy "Users can join teams"
  on public.team_members for insert
  with check ( auth.uid() = user_id );

create policy "Users can leave teams"
  on public.team_members for delete
  using ( auth.uid() = user_id );


-- 7. TOURNAMENT REGISTRATIONS TABLE (New)
create table public.tournament_registrations (
  id bigint generated by default as identity primary key,
  tournament_id bigint references public.tournaments(id) on delete cascade not null,
  team_id bigint references public.teams(id) on delete cascade not null,
  registered_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(tournament_id, team_id)
);

-- Enable RLS
alter table public.tournament_registrations enable row level security;

-- Policies
create policy "Registrations viewable by everyone"
  on public.tournament_registrations for select
  using ( true );

create policy "Team members can register"
  on public.tournament_registrations for insert
  with check ( 
    exists (
      select 1 from public.team_members 
      where team_members.team_id = tournament_registrations.team_id
      and team_members.user_id = auth.uid()
    )
  );

-- 8. CREATORS TABLE
create table public.creators (
  id bigint generated by default as identity primary key,
  name text not null,
  platform text not null,
  followers text not null,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.creators enable row level security;

-- Policies for creators
create policy "Creators are viewable by everyone."
  on public.creators for select
  using ( true );

create policy "Admins and Super Admins can manage creators."
  on public.creators for all
  using ( 
    auth.uid() in (
      select id from public.profiles 
      where role in ('admin', 'super_admin')
    )
  );


-- 6. SEED DATA (Initial Content)

-- Seed Tournaments
insert into public.tournaments (name, game, prize, start_date) values
('Valorant Masters', 'Valorant', '$100,000', 'Feb 15, 2026'),
('Apex Legends Global', 'Apex Legends', '$75,000', 'Feb 22, 2026'),
('CS2 Pro League', 'Counter-Strike 2', '$250,000', 'Mar 01, 2026'),
('Rocket League Championship', 'Rocket League', '$50,000', 'Mar 10, 2026');

-- Seed Teams
insert into public.teams (name, wins, members_count) values
('Liquid Pulse', 42, 5),
('Blackout Gaming', 38, 6),
('Void Runners', 31, 4),
('Echo Protocol', 29, 5);
