-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. ENUMS & ROLES
create type user_role as enum ('super_admin', 'admin', 'user');

-- 2. PROFILES TABLE (Extends auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  avatar_url text,
  role user_role default 'user'::user_role,
  updated_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on profiles
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on public.profiles for update
  using ( auth.uid() = id );

-- Trigger to handle new user signup automatically
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, avatar_url, role)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url', 'user');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- 3. TOURNAMENTS TABLE
create table public.tournaments (
  id bigint generated by default as identity primary key,
  name text not null,
  game text not null,
  prize text not null,
  start_date text not null,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.tournaments enable row level security;

-- Policies for tournaments
create policy "Tournaments are viewable by everyone."
  on public.tournaments for select
  using ( true );

create policy "Admins and Super Admins can insert tournaments."
  on public.tournaments for insert
  with check ( 
    auth.uid() in (
      select id from public.profiles 
      where role in ('admin', 'super_admin')
    )
  );

create policy "Admins and Super Admins can update tournaments."
  on public.tournaments for update
  using ( 
    auth.uid() in (
      select id from public.profiles 
      where role in ('admin', 'super_admin')
    )
  );

create policy "Admins and Super Admins can delete tournaments."
  on public.tournaments for delete
  using ( 
    auth.uid() in (
      select id from public.profiles 
      where role in ('admin', 'super_admin')
    )
  );


-- 4. TEAMS TABLE
create table public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  wins integer default 0,
  members_count integer default 1,
  logo_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.teams enable row level security;

-- Policies for teams
create policy "Teams are viewable by everyone."
  on public.teams for select
  using ( true );

create policy "Admins and Super Admins can manage teams."
  on public.teams for all
  using ( 
    auth.uid() in (
      select id from public.profiles 
      where role in ('admin', 'super_admin')
    )
  );


-- 5. CREATORS TABLE
create table public.creators (
  id bigint generated by default as identity primary key,
  name text not null,
  platform text not null,
  followers text not null,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.creators enable row level security;

-- Policies for creators
create policy "Creators are viewable by everyone."
  on public.creators for select
  using ( true );

create policy "Admins and Super Admins can manage creators."
  on public.creators for all
  using ( 
    auth.uid() in (
      select id from public.profiles 
      where role in ('admin', 'super_admin')
    )
  );


-- 6. SEED DATA (Initial Content)

-- Seed Tournaments
insert into public.tournaments (name, game, prize, start_date) values
('Valorant Masters', 'Valorant', '$100,000', 'Feb 15, 2026'),
('Apex Legends Global', 'Apex Legends', '$75,000', 'Feb 22, 2026'),
('CS2 Pro League', 'Counter-Strike 2', '$250,000', 'Mar 01, 2026'),
('Rocket League Championship', 'Rocket League', '$50,000', 'Mar 10, 2026');

-- Seed Teams
insert into public.teams (name, wins, members_count) values
('Liquid Pulse', 42, 5),
('Blackout Gaming', 38, 6),
('Void Runners', 31, 4),
('Echo Protocol', 29, 5);
