import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load .env.local
try {
    const envPath = path.resolve(__dirname, '../.env.local');
    const envConfig = fs.readFileSync(envPath, 'utf8');
    envConfig.split('\n').forEach(line => {
        const [key, ...valueParts] = line.split('=');
        if (key && valueParts.length > 0) {
            const value = valueParts.join('='); // Rejoin in case value contains =
            process.env[key.trim()] = value.trim();
        }
    });
} catch (e) {
    console.error('Error loading .env.local:', e);
}

// Dynamic import after env vars are set
let sql;
async function loadSql() {
    const module = await import('../src/lib/supabase.js');
    sql = module.default;
}

async function migrate() {
    try {
        await loadSql();
        console.log('Starting migration...');

        // 1. Add join_code to teams
        await sql`
            ALTER TABLE public.teams 
            ADD COLUMN IF NOT EXISTS join_code TEXT UNIQUE;
        `;
        console.log('Added join_code to teams.');

        // 2. Create team_members table
        await sql`
            CREATE TABLE IF NOT EXISTS public.team_members (
                id bigint generated by default as identity primary key,
                team_id bigint references public.teams(id) on delete cascade not null,
                user_id uuid references public.profiles(id) on delete cascade not null,
                role text default 'member',
                joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
                UNIQUE(user_id)
            );
        `;

        // Enable RLS for team_members
        await sql`ALTER TABLE public.team_members ENABLE ROW LEVEL SECURITY;`;

        // Policies for team_members
        // View: everyone can see members
        await sql`
            DROP POLICY IF EXISTS "Team members are viewable by everyone" ON public.team_members;
        `;
        await sql`
            CREATE POLICY "Team members are viewable by everyone" ON public.team_members FOR SELECT USING (true);
        `;

        // Insert: Users can join (insert themselves)
        await sql`
            DROP POLICY IF EXISTS "Users can join teams" ON public.team_members;
        `;
        await sql`
            CREATE POLICY "Users can join teams" ON public.team_members FOR INSERT WITH CHECK (auth.uid() = user_id);
        `;

        // Delete: Users can leave (delete themselves)
        await sql`
            DROP POLICY IF EXISTS "Users can leave teams" ON public.team_members;
        `;
        await sql`
            CREATE POLICY "Users can leave teams" ON public.team_members FOR DELETE USING (auth.uid() = user_id);
        `;

        console.log('Created team_members table and policies.');

        // 3. Create tournament_registrations table
        await sql`
            CREATE TABLE IF NOT EXISTS public.tournament_registrations (
                id bigint generated by default as identity primary key,
                tournament_id bigint references public.tournaments(id) on delete cascade not null,
                team_id bigint references public.teams(id) on delete cascade not null,
                registered_at timestamp with time zone default timezone('utc'::text, now()) not null,
                UNIQUE(tournament_id, team_id)
            );
        `;

        // Enable RLS for tournament_registrations
        await sql`ALTER TABLE public.tournament_registrations ENABLE ROW LEVEL SECURITY;`;

        // Policies for tournament_registrations
        await sql`
            DROP POLICY IF EXISTS "Registrations viewable by everyone" ON public.tournament_registrations;
        `;
        await sql`
            CREATE POLICY "Registrations viewable by everyone" ON public.tournament_registrations FOR SELECT USING (true);
        `;

        // Insert: Team members can register their team
        await sql`
            DROP POLICY IF EXISTS "Team members can register" ON public.tournament_registrations;
        `;
        await sql`
            CREATE POLICY "Team members can register" ON public.tournament_registrations FOR INSERT WITH CHECK (
                EXISTS (
                    SELECT 1 FROM public.team_members 
                    WHERE team_members.team_id = tournament_registrations.team_id
                    AND team_members.user_id = auth.uid()
                )
            );
        `;

        console.log('Created tournament_registrations table and policies.');

        // 4. Update teams policies to allow creation
        await sql`
            DROP POLICY IF EXISTS "Users can insert teams" ON public.teams;
        `;
        await sql`
            CREATE POLICY "Users can insert teams" ON public.teams FOR INSERT TO authenticated WITH CHECK (true);
        `;

        console.log('Updated teams policies.');

        console.log('Migration completed successfully.');
        process.exit(0);
    } catch (error) {
        console.error('Migration failed:', error);
        console.error(error);
        process.exit(1);
    }
}

migrate();
